#! /usr/bin/env python

from libcloud.types import Provider 
from libcloud.providers import get_driver 
import ConfigParser

config = ConfigParser.RawConfigParser()
config.read('config/felicity.ini')
user = config.get('Rackspace', 'user')
key = config.get('Rackspace', 'key')

Driver = get_driver(Provider.RACKSPACE)
conn = Driver(user, key)


print conn.ex_limits()
