#! /usr/bin/env python

from boto.s3.connection import S3Connection
import sys
import re

conn = S3Connection()

bucket_name =sys.argv[1]

bucket = conn.get_bucket(bucket_name)

for key in bucket.list():
	print key
