#! /usr/bin/env python

from boto.s3.connection import S3Connection
import sys
import re

server = sys.argv[1]

conn = S3Connection()

rs = conn.get_all_buckets()

for b in rs:
	matchObj = re.match(server, b.name)
	if matchObj:
		print b.name
