#! /usr/bin/env python

import cloudfiles, os, sys, re

server = sys.argv[1]

user = os.getenv('CLOUDFILES_USERNAME')
key  = os.getenv('CLOUDFILES_APIKEY')
conn = cloudfiles.get_connection(user, key)

containers = conn.get_all_containers()

for container in containers:
	matchObj = re.search(server, container.name)
	if matchObj:
		print container.name
