#!/bin/bash

SERVER=$1
EMAIL=$2
BACKUPPROVIDER=$3

# Source the creds
source /usr/local/etc/backup_restore_creds

# TODO: abstract this so restoring from CF works
sh /usr/local/bin/backup_restore $SERVER $BACKUPPROVIDER > $HOME/emailmessage.txt

if [ $BACKUPPROVIDER == "Amazon" ]; then
  unset AWS_ACCESS_KEY_ID
  unset AWS_SECRET_ACCESS_KEY
else
  unset CLOUDFILES_USERNAME
  unset CLOUDFILES_APIKEY
fi

unset PASSPHRASE

rm /usr/local/etc/backup_restore_creds

# Cleanup
sed -i '/^Copying duplicity/d' $HOME/emailmessage.txt
sed -i '/^Deleting local/d' $HOME/emailmessage.txt
sed -i '/^Local and Remote metadata/d' $HOME/emailmessage.txt
sed -i '/^Archive dir/d' $HOME/emailmessage.txt
sed -i '/^Connecting with backend/d' $HOME/emailmessage.txt
sed -i '/^Synchronizing remote metadata to local cache/d' $HOME/emailmessage.txt

# Email the report
SUBJECT="Backup restore of $SERVER"

mail -s "$SUBJECT" "$EMAIL" < $HOME/emailmessage.txt

# Remove the email log
rm $HOME/emailmessage.txt

# Remove the duplicity cache
rm -rf $HOME/.cache/duplicity
